### ISSUE TITLE
Attempting to Z to a directory that you have not been to fails.

### ISSUE THREAD

**Issue by Kethku** [vors/ZLocation#15]
If I have been to directory A but have not been to a directory B which is in A and my current path is A, calling "z B" does not work.

**Comment by vors** [comment]
It would probably be useful for the scenario: completely replace `cd` by `z`. I personally prefer being explicit about my intention and distinguish `cd` from `z`.

**Comment by Devagamster** [comment]
Is there any reason why it can't do both? I don't think it would effect the functionality of the tool much if trying to jump to locations in the same directory or locations which are rooted worked. And that way you can use it if you like for both or use cd like you say. I don't know, just a thought.

Sent from Windows Mail

**Comment by vors** [comment]
it would affect functionality: 
- tab-completion should be altered accordingly and will contain all relative files
- if I `z`, my intention is almost always to go outside of the current folder. Then you need to figure out the right weight strategy for local files vs files from db.

Overall, having two separate commands simplifies both scenarios.
I would be very careful about adding any new capabilities to the core, but it would be great to explore options to enable plugin / extensions model. Would it work?

**Comment by Devagamster** [comment]
Sorry for my brief hiatus. I think that a plugin system would work perfectly. Having never written a plugin system in powershell for a script however I don't really have a good idea of what that would look like. I am willing to help in what time I have though!

**Comment by eugenesvk** [comment]
Got here after reading these issues of using [**Jump-Location**](https://github.com/tkellogg/Jump-Location) with [**PSReadLine**](https://github.com/lzybkr/PSReadLine) (https://github.com/lzybkr/PSReadLine/issues/169 and https://github.com/tkellogg/Jump-Location/issues/56), and though they seem to be resolved now, Jump-Location suffers from the same issue. So I  wanted to leave some feedback as lack of `cd` replacement is an unnecessary complication of having to remember two commands for the same basic function of navigating folders.

In this regard I don't really understand the point of your mental separation between going outside the current folder vs inside. In my mind it's the same thing — **folder navigation**. And the only reason I have to separate `z/j` from `cd` is because:

- `cd` is completely dysfunctional. Re. `cd` it's oftentimes easier for me to use a `Win+3` shortcut to open the favorite folder No3 in explorer, type a few "first folder letter/Enter" to navigate where I want and then paste results to my command line (or use "Open Powershell here" context menu that I got thanks to ConEmu).
- while the replacements for some reason pay any attention to that dysfunctional command instead of just completely taking over.

> but it would be great to explore options to enable plugin / extensions model

A plugin to a plugin :) To me that's already a narrow-enough plugin that should have this function as a core. Would it maybe be better to add this as an optional toggle instead so that users could keep using that old and dysfunctional `cd` if they like?

> tab-completion should be altered accordingly and will contain all relative files

Yes, and to make it perfect it would be great to have `MenuComplete` function from PSReadLine that shows all available options that you can navigate with arrow keys. Also, after choosing a given favorite folder from the list of folders **ZLocation** remembers, it would be great if I could continue to type the first letter and hit Tab again to invoke yet another completion menu that would show the folders down the path.

For example, if my **ZLocation** database has **C:\Dev\Apps**, but doesn't have the subsequent **C:\Dev\Apps\7zip**, I could `z app{Tab once or twice}{/ or \}7z{Tab}` to get a full completion to the 7zip folder
The `/` or `\` are needed so that Z understands it should stop cycling through different variants of `app` from it's database and start behaving like a `cd` completion for subsequent paths. Also, if Z had a `MenuComplete` function, instead of multiple {Tabs} you could just use arrow keys to navigate the matching completions.

**Comment by vors** [comment]
@eugenesvk great feedback, thank you!

**Comment by Jaykul** [comment]
I don't understand what the problem is with tab-expansion.

I modified the `if (-not $pushDone) {` at the bottom of Set-ZLocation to do a last-ditch attempt to find the path, and it seems to work OK for me (but I guess I don't auto-complete that often). Can you be more explicit about what's wrong with this?

```posh
function Set-ZLocation()
{
    Register-PromptHook

    if (-not $args) {
        $args = @()
    }

    # Special case to enable Pop-Location.
    if (($args.Count -eq 1) -and ($args[0] -eq '-')) {
        Pop-ZLocation
        return
    }

    $matches = Find-Matches (Get-ZLocation) $args
    $pushDone = $false
    foreach ($match in $matches) {
        if (Test-path $match) {
            Push-Location $match
            $pushDone = $true
            break
        } else {
            Write-Warning "There is no path $match on the file system. Removing obsolete date from datebase."
            Remove-ZLocation $match
        }
    }
    if (-not $pushDone) {
        if (($args.Count -eq 1) -and (Test-Path "$args")) {
            Push-Location "$args"
        } else {
            Write-Warning "Cannot find matching location"
        }
    }
}
```

**Comment by vors** [comment]
@Jaykul care to send a PR for it?
