### ISSUE TITLE
Jump to number fails

### ISSUE THREAD

**Issue by LTruijens** [vors/ZLocation#25]
ZLocation seems to be having problems with PowerShell 5 Production Preview. It is, in some cases, unable to jump given just a number. 

``` powershell
PS> mkdir 7\test
PS> cd 7\test
PS> cd ..\..
PS> Get-ZLocation
Name          Value
------          ----
1      C:\temp
3       C:\temp\7\test
PS> z 7
WARNING: Cannot find matching location
```

It does work again if the folder with the number is in the jumpstats

``` powershell
PS> cd 7
PS> cd ..
PS> Get-ZLocation
Name          Value
------          ----
1      C:\temp
3       C:\temp\7\test
4       C:\temp\7
PS> z 7
```

PS: Jump-Location has the same issue

**Comment by vors** [comment]
Oh very interesting! Sorry for not looking at it for 3 years - it somehow slipped out of my attention.

**Comment by theaquamarine** [comment]
I'm not 100% on what the issue is here: 
- If the expected result of the top example is to end up in `C:\temp\7`, then I think ZLocation did the right thing: `C:\temp\7` isn't a known location at that point (though its parent and child directories are), so ZLocation wouldn't jump to it. The ability to move to unknown directories added since this was opened means ZLocation would now move to `C:\temp\7` now, as it'd be treated as a direct reference to the child directory `7`.

- If the expected result is to end up `C:\temp\7\test`, then that's because [the last step of `Test-FuzzyMatch`](https://github.com/vors/ZLocation/blob/6fa70c69b5335ee2bcf69d77939bb760cb6ae3c9/ZLocation/ZLocation.Search.psm1#L120-L121) requires the query (`7`) to be part of the leaf of the path (`test`). Whether that's right could be debated, but ZLocation's functioned that way at least as long as there's been a separate search module (https://github.com/vors/ZLocation/commit/812596da4bab159e4caec16da2ed1a526ede930d#diff-93df13f76ff52d17e115d75e3c549004R44-R45)
```powershell
$search = ipmo .\ZLocation\ZLocation.Search.psm1 -PassThru
& $search { Test-Fuzzymatch 'C:\temp\7\test' 7 } #False
& $search { Test-Fuzzymatch 'C:\temp\foo\test' foo } #False
```

**Comment by vors** [comment]
@theaquamarine feel free to close, this seems to be super old anyway
